#!/bin/bash

set -euo pipefail

K8S_MINOR_VERSION="v1.36"

echo "============================================================"
echo " Kubernetes Worker Node Preparation"
echo "============================================================"

# ============================================================
# SUDO
# ============================================================

sudo -v

# ============================================================
# UPDATE
# ============================================================

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# ============================================================
# BASIC PACKAGES
# ============================================================

sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gpg \
    gnupg \
    jq \
    conntrack \
    socat \
    ebtables \
    ethtool \
    iproute2 \
    iputils-ping \
    net-tools \
    bash-completion \
    software-properties-common \
    lsb-release \
    containernetworking-plugins \
    runc

# ============================================================
# SWAP
# ============================================================

sudo swapoff -a

sudo sed -ri '/[[:space:]]swap[[:space:]]/ s/^/#/' /etc/fstab

# ============================================================
# KERNEL MODULES
# ============================================================

sudo tee /etc/modules-load.d/k8s.conf > /dev/null <<EOF
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# ============================================================
# SYSCTL
# ============================================================

sudo tee /etc/sysctl.d/k8s.conf > /dev/null <<EOF
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF

sudo sysctl --system

# ============================================================
# CONTAINERD
# ============================================================

sudo apt-get install -y containerd

sudo mkdir -p /etc/containerd

containerd config default \
    | sudo tee /etc/containerd/config.toml > /dev/null

sudo sed -i \
    's/SystemdCgroup = false/SystemdCgroup = true/g' \
    /etc/containerd/config.toml

sudo systemctl daemon-reload
sudo systemctl enable containerd
sudo systemctl restart containerd

sleep 3

if ! sudo systemctl is-active --quiet containerd; then
    echo "ERROR: containerd is not running."
    sudo systemctl status containerd --no-pager
    exit 1
fi

echo ""
echo "containerd:"
containerd --version

# ============================================================
# KUBERNETES REPOSITORY
# ============================================================

sudo mkdir -p -m 755 /etc/apt/keyrings

sudo rm -f /etc/apt/sources.list.d/kubernetes.list

curl -fsSL \
    "https://pkgs.k8s.io/core:/stable:/${K8S_MINOR_VERSION}/deb/Release.key" \
    | sudo gpg --dearmor --yes \
    -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo \
"deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${K8S_MINOR_VERSION}/deb/ /" \
| sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null

sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list

# ============================================================
# KUBERNETES
# ============================================================

sudo apt-get update

sudo apt-get install -y \
    kubelet \
    kubeadm \
    kubectl

sudo apt-mark hold kubelet kubeadm kubectl

sudo systemctl enable kubelet

# ============================================================
# VERIFICATION
# ============================================================

echo ""
echo "============================================================"
echo " Worker Node Preparation Completed"
echo "============================================================"

echo ""
echo "kubeadm:"
kubeadm version

echo ""
echo "kubectl:"
kubectl version --client

echo ""
echo "kubelet:"
kubelet --version

echo ""
echo "containerd:"
containerd --version

echo ""
echo "============================================================"
echo " NEXT STEP"
echo "============================================================"
echo ""
echo "Run the kubeadm join command generated by the"
echo "Control Plane on this worker node."
echo ""